
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  name: providers.azure.crossplane.io
spec:
  additionalPrinterColumns:
  - JSONPath: .spec.credentialsSecretRef.name
    name: SECRET-NAME
    priority: 1
    type: string
  group: azure.crossplane.io
  names:
    kind: Provider
    listKind: ProviderList
    plural: providers
    singular: provider
  scope: Cluster
  subresources: {}
  validation:
    openAPIV3Schema:
      description: A Provider configures an Azure 'provider', i.e. a connection to
        a particular Azure account using a particular Azure Service Principal.
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: A ProviderSpec defines the desired state of a Provider.
          properties:
            credentialsSecretRef:
              description: Azure service principal credentials json secret key reference
                A Secret containing JSON encoded credentials for an Azure Service
                Principal that will be used to authenticate to this Azure Provider.
              properties:
                key:
                  description: The key to select.
                  type: string
                name:
                  description: Name of the secret.
                  type: string
                namespace:
                  description: Namespace of the secret.
                  type: string
              required:
              - key
              - name
              - namespace
              type: object
          required:
          - credentialsSecretRef
          type: object
      type: object
  version: v1alpha2
  versions:
  - name: v1alpha2
    served: true
    storage: true
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
